### ISSUE TITLE
Build error on Lineage_16.0 - H812, usu 

### ISSUE THREAD

**Issue by sdembis** [Suicide-Squirrel/issues_a10#17]
Hi steadfasterX:  Appreciate some help with the following error.  Thanks, S.

[ 98% 94457/96103] Target Java: /home/...n_intermediates/classes-full-debug.jar
FAILED: /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes-full-debug.jar ) && (rm -rf /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/anno ) && (mkdir -p /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/ ) && (mkdir -p /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/anno ) && (if [ -s /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/java-source-list ] ; then /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/classes-header.jar  -d /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes -s /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/anno  -source 1.8 -target 1.8 -g:source,lines  \\@/home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/java-source-list  || ( rm -rf /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes-full-debug.jar     @<(find /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/target/common/obj/JAVA_LIBRARIES/ims-ext-common_intermediates/classes; echo \"-C /home/steve/Desktop/LOS_16.0_LG_G4_H812_USU/out/empty .\") )"
vendor/codeaurora/telephony/ims/src/org/codeaurora/ims/QtiImsExtManager.java:41: error: cannot find symbol
import com.android.ims.ImsManager;
                      ^
  symbol:   class ImsManager
  location: package com.android.ims
vendor/codeaurora/telephony/ims/src/org/codeaurora/ims/QtiImsExtManager.java:283: error: cannot find symbol
            if (ImsManager.getInstance(mContext, phoneId).getImsServiceState() !=
                ^
  symbol:   variable ImsManager
  location: class QtiImsExtManager
2 errors
[ 98% 94461/96103] //art/compiler:libart-compiler link libart-compiler.so
Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
[ 98% 94462/96103] //art/compiler:liba...compiler link libart-compiler.so [arm]
Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
ninja: build stopped: subcommand failed.
08:57:14 ninja failed with: exit status 1

**Comment by sdembis** [comment]
Error solved - because the build failed after the P_asb_2023-11 security updates, I thought it might be related to one of the security patches.  After removing the /vendor/codeaurora folder and repo-syncing again and troubleshooting the repopicks for the Nov. updates, the culprit appears to be related to a corruption in the 'codeauroa' that developed along the way.

**Comment by steadfasterX** [comment]
glad u solved it ;)
