### ISSUE TITLE
Location RIL bug (Switch off Location switches off RIL)

### ISSUE THREAD

**Issue by aoleary** [Suicide-Squirrel/issues_a10#9]
[Location-RIL bug.txt](https://github.com/LGgFour/issues_a10/files/7898474/Location-RIL.bug.txt)

Switching off Location disables the RIL

**Comment by steadfasterX** [comment]
guess we fixed that no? @aoleary

**Comment by aoleary** [comment]
Yes fixed

**Comment by aoleary** [comment]
Fixed with this commit: https://github.com/aoleary/device_lge_g4-common/commit/ea787c82bcec46ac9c934811253d06525841c2af
